export const tags = [
  { name: "JavaScript" },
  { name: "Python" },
  { name: "Java" },
  { name: "C++" },
  { name: "HTML" },
  { name: "CSS" },
  { name: "React" },
  { name: "Node.js" },
  { name: "Angular" },
  { name: "Vue.js" },
  { name: "TypeScript" },
  { name: "Ruby" },
  { name: "PHP" },
  { name: "NextJs" },
  { name: "Swift" },
  { name: "Go" },
  { name: "SQL" },
  { name: "MongoDB" },
  { name: "Firebase" },
  { name: "Django" },
  { name: "Flask" },
  { name: "Spring" },
  { name: "Express.js" },
  { name: "Bootstrap" },
  { name: "Tailwind CSS" },
  { name: "SASS" },
  { name: "Redux" },
  { name: "GraphQL" },
  { name: "RESTful API" },
  { name: "OAuth" },
  { name: "JWT" },
  { name: "Blockchain" },
  { name: "Cybersecurity" },
  { name: "Ethical Hacking" },
  { name: "Penetration Testing" },
  { name: "Cryptography" },
  { name: "Data Science" },
  { name: "Machine Learning" },
  { name: "Artificial Intelligence" },
  { name: "Big Data" },
  { name: "Data Visualization" },
  { name: "Data Analysis" },
  { name: "Data Engineering" },
  { name: "Natural Language Processing" },
  { name: "Computer Vision" },
  { name: "Deep Learning" },
  { name: "Neural Networks" },
  { name: "Reinforcement Learning" },
  { name: "Server-side Development" },
  { name: "Client-side Development" },
  { name: "Full-stack Development" },
  { name: "DevOps" },
  { name: "Microservices" },
  { name: "Containers" },
  { name: "Docker" },
  { name: "Kubernetes" },
  { name: "Serverless" },
  { name: "AWS" },
  { name: "Azure" },
  { name: "Google Cloud Platform" },
  { name: "DigitalOcean" },
  { name: "Heroku" },
  { name: "Linux" },
  { name: "Windows" },
  { name: "MacOS" },
  { name: "Git" },
  { name: "GitHub" },
  { name: "GitLab" },
  { name: "Bitbucket" },
  { name: "Version Control" },
  { name: "Agile" },
  { name: "Scrum" },
  { name: "Kanban" },
  { name: "CI/CD" },
  { name: "Testing" },
  { name: "Unit Testing" },
  { name: "Integration Testing" },
  { name: "End-to-End Testing" },
  { name: "TDD" },
  { name: "BDD" },
  { name: "Code Quality" },
  { name: "Code Review" },
  { name: "Static Analysis" },
  { name: "Refactoring" },
  { name: "Design Patterns" },
  { name: "Algorithms" },
  { name: "Data Structures" },
  { name: "Competitive Programming" },
  { name: "Interview Preparation" },
  { name: "Career Development" },
  { name: "Freelancing" },
  { name: "Remote Work" },
  { name: "Productivity" },
  { name: "Time Management" },
  { name: "Soft Skills" },
  { name: "Communication Skills" },
  { name: "Problem Solving" },
  { name: "Critical Thinking" },
  { name: "Leadership" },
  { name: "Teamwork" },
  { name: "Self-learning" },
  { name: "Motivation" },
  { name: "Work-life Balance" },
  { name: "Health and Wellness" },
];
